//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.2840.1515.g1b7ab74";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1515;
        public const string CEF_COMMIT_HASH = "1b7ab74bcf49ff34daf39be20bb34f4434dd5b32";
        
        public const int CHROME_VERSION_MAJOR = 54;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 2840;
        public const int CHROME_VERSION_PATCH = 90;
        
        public const string CEF_API_HASH_UNIVERSAL = "5fd9b32e472bbfaf25a50a2d3b5d3232bb586295";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "d95369639510d29b872f55fb6dc4ee5beb0aebce";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "240821fb402cbb5978d94e99e1e390879ecc79cb";
        public const string CEF_API_HASH_PLATFORM_LINUX = "99e8ea64a74fb21a91ffb416dc0b3c827b8e220b";
    }
}
