//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.2704.1416.g6549316";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1416;
        public const string CEF_COMMIT_HASH = "654931637cb04c2f404b7ee1b0dc8e2f4f4cc1bb";
        
        public const int CHROME_VERSION_MAJOR = 51;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 2704;
        public const int CHROME_VERSION_PATCH = 63;
        
        public const string CEF_API_HASH_UNIVERSAL = "0b16f480992a3e268258b39d728782f2349edab2";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "8e32000be3c4a4057057f32973e413b3c9517a9c";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "698ca8f4b36d446333755ba6431ba0ab42a814cb";
        public const string CEF_API_HASH_PLATFORM_LINUX = "9d132433b77eaf33fc9f0fc9059a6eae3d386e63";
    }
}
