//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.2704.1425.gf05c7b3";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1425;
        public const string CEF_COMMIT_HASH = "f05c7b3d5713a815fb5e4a7b3febf1082c15cbe9";
        
        public const int CHROME_VERSION_MAJOR = 51;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 2704;
        public const int CHROME_VERSION_PATCH = 63;
        
        public const string CEF_API_HASH_UNIVERSAL = "e8e72d53ce6acfc5de467fb7fe641ae279cbc9e9";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "d0eea167f9276cdb31a72630db1e805680492f55";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "5f95df7ec4a27c8971f1dd5209d680b83a55cd0d";
        public const string CEF_API_HASH_PLATFORM_LINUX = "51df4a1f4e3a1c3d73b8e5e211e920bb6f7fdb34";
    }
}
