//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.2454.1324.g3e87c99";
        public const int CEF_VERSION_MAJOR = 3;
        public const int COPYRIGHT_YEAR = 2015;
        public const int CEF_COMMIT_NUMBER = 1324;
        public const string CEF_COMMIT_HASH = "3e87c9900911d056efebd0c5cf33f96a26251c20";
        
        public const int CHROME_VERSION_MAJOR = 45;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 2454;
        public const int CHROME_VERSION_PATCH = 62;
        
        public const string CEF_API_HASH_UNIVERSAL = "98b02e6018dabfae661585c31bf7cf1f1b303a6a";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "b15b29a703533efc5b328ffc771f077f217b5edd";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "ad58fa216462c28aa4cfa0a5defe935c21f6e551";
        public const string CEF_API_HASH_PLATFORM_LINUX = "f0c9f7898286aee42eff4d997648f375332ec184";
    }
}
