//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.2357.1267.g75b5dd4";
        public const int CEF_VERSION_MAJOR = 3;
        public const int COPYRIGHT_YEAR = 2015;
        public const int CEF_COMMIT_NUMBER = 1267;
        public const string CEF_COMMIT_HASH = "75b5dd4d813270502e51f90aa92d04cc9c37cf65";
        
        public const int CHROME_VERSION_MAJOR = 43;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 2357;
        public const int CHROME_VERSION_PATCH = 18;
        
        public const string CEF_API_HASH_UNIVERSAL = "2b3193123e3383250ab2063849efe7db537bd4c1";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "27c1156f5f9b4d4271ec2e146a1e10fb47a01712";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "f6e8bce3f2a055cb80402692d500986607463e32";
        public const string CEF_API_HASH_PLATFORM_LINUX = "e50a8044ea7deea0578a41f602f412826eb0ea0a";
    }
}
