//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.2454.1322.gf71ad5d";
        public const int CEF_VERSION_MAJOR = 3;
        public const int COPYRIGHT_YEAR = 2015;
        public const int CEF_COMMIT_NUMBER = 1322;
        public const string CEF_COMMIT_HASH = "f71ad5dec98f4e9fe288ea5d1a5a6459937a3f6b";
        
        public const int CHROME_VERSION_MAJOR = 45;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 2454;
        public const int CHROME_VERSION_PATCH = 62;
        
        public const string CEF_API_HASH_UNIVERSAL = "f410f1c2669d2ba99edcd2967f19b748f447967e";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "5afaf5b17206e8a9beda0c17c3f58925ff13f34f";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "16f47611c82f0889dddbdf532663519cae235ef2";
        public const string CEF_API_HASH_PLATFORM_LINUX = "a3ecb134fbd4f7c59430a3babc532f5da0953953";
    }
}
