//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_REVISION = 1902;
        public const int COPYRIGHT_YEAR = 2014;
        
        public const int CHROME_VERSION_MAJOR = 39;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 2171;
        public const int CHROME_VERSION_PATCH = 36;
        
        public const string CEF_API_HASH_UNIVERSAL = "8efd129f4afc344bd04b2feb7f73a149b6c4e27f";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "5c7f3e50ff5265985d11dc1a466513e25748bedd";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "6813214accbf2ebfb6bdcf8d00654650b251bf3d";
        public const string CEF_API_HASH_PLATFORM_LINUX = "2bc564c3871965ef3a2531b528bda3e17fa17a6d";
    }
}
